[pytest]
pythonpath = .
testpaths = proxy/test
markers =
    abuse: Tests de sécurité, injections et abus (prompt injection, jailbreak).
	ai_call: Tests effectué avec l appel à l IA (clé API du LLM nécessaire)
	integration: Tests d integration
	unitaire: Tests unitaires
