openapi: 3.0.3
info:
  title: Meeting Summary API
  version: 1.0.1
  description: API to generate structured meeting summaries

paths:
  /meeting-summary:
    post:
      summary: Generate meeting summary
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - meeting_id
                - transcript
		- language
              properties:
                meeting_id:
                  type: string
                transcript:
                  type: string
                language:
                  type: string
                  example: "fr"
		  enum: ["fr", "en"]
      responses:
        "200":
          description: Summary generated
          content:
            application/json:
              schema:
                type: object
		additionalProperties: false
		required:
		  - meeting_id
		  - summary
		  - actions 
                properties:
                  meeting_id:
                    type: string
                  summary:
                    type: string
		  action:
		    type: array
		    items:
                      type: object
                      additionalProperties: false
                      required:
                        - owner
                        - description
                      properties:
                        owner:
                          type: string
                        description:
                          type: string
        "400":
          description: Bad request
        "401":
          description: Unauthorized
	"422":
	  description: Validation error
        "500":
          description: Internal server error
